services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    image: react_frontend
    container_name: frontend
    ports:
      - "5173:5173"
    command: npm run dev
    environment:
      - VITE_PORT=5173
