version: "3.8"

services:
  frontend:
    build:
      context: ./frontend
    container_name: react_frontend
    ports:
      - "3000:3000"
    networks:
      - app-network

  backend:
    build:
      context: ./backend
    container_name: laravel_backend
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    networks:
      - app-network

  db:
    image: mysql:8
    container_name: mysql_db
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app-network
    ports:
      - "3306:3306"

  redis:
    image: redis:alpine
    container_name: redis
    networks:
      - app-network
    expose:
      - "6379"

networks:
  app-network:
    driver: bridge

volumes:
  mysql_data:
