services:
  backend:
    image: laravel_backend
    container_name: backend
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/var/www/html


# services:
#   nginx:
#     image: nginx:latest
#     container_name: nginx
#     volumes:
#       - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
#       - ./backend:/var/www/html
#     ports:
#       - "80:80"
#     depends_on:
#       - php-fpm

#   php-fpm:
#     image: php:7.4-fpm
#     container_name: php-fpm
#     volumes:
#       - ./backend:/var/www/html
#     expose:
#       - "9000"

#   app:
#     image: laravel-app
#     container_name: laravel-app
#     build:
#       context: .
#       dockerfile: Dockerfile
#     volumes:
#       - ./backend:/var/www/html
#     depends_on:
#       - php-fpm
